<?php

declare(strict_types=1);

namespace JLucki\ODM\Spark\Schema;

use Exception;
use function count;

/**
 * The UpdateSchemaFactory renders an update schema array for the table formatted as per DynamoDB
 * requirements as outlined in the PHP SDK:
 *
 * https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.DynamoDb.DynamoDbClient.html#_updateTable
 *
 * This schema is generated by comparing the original schema as provided by describeTable to the
 * current schema on the ItemInterface.
 *
 * Class SchemaFactory
 * @package JLucki\ODM\Spark\Schema
 */
class UpdateSchemaFactory
{

    /** @var array<string, mixed> */
    private array $updateSchema;

    public function __construct(
        /** @var array<string, mixed> */
        private array $describedSchema,
        /** @var array<string, mixed> */
        private array $currentSchema,
    ) {
        $this->renderSchema();
    }

    /**
     * @return array<string, mixed>
     */
    public function getUpdateSchema(): array
    {
        return $this->updateSchema;
    }

    private function renderSchema(): void
    {
        $this->setSchemaSkeleton();

        $this->generateSchemaVariation();
    }

    private function setSchemaSkeleton()
    {
        $schemaSkeleton = new Skeleton(
            $this->currentSchema['TableName'],
            $this->currentSchema['ProvisionedThroughput']['ReadCapacityUnits'],
            $this->currentSchema['ProvisionedThroughput']['WriteCapacityUnits'],
        );
        $this->updateSchema = $schemaSkeleton->getArray(false);
    }

    private function generateSchemaVariation()
    {
        foreach ($this->currentSchema as $parameter => $value) {
            switch ($parameter) {
                case 'TableName':
                    $this->setTableName();
                    break;
                case 'KeySchema':
                    $this->setKeySchema();
                    break;
                case 'AttributeDefinitions':
                    $this->setAttributeDefinitions();
                    break;
                case 'ProvisionThroughput':
                    $this->setProvisionThroughput();
                    break;
                case 'GlobalSecondaryIndexes':
                    $this->setGlobalSecondaryIndexes();
                    break;
                default:
                    // unsupported parameter, safe to ignore
            }
        }
    }

    /**
     * @throws Exception
     */
    private function setTableName(): void
    {
        if ($this->currentSchema['TableName'] !== $this->describedSchema['TableName']) {
            throw new Exception('updateTable doesn\'t support changing the table name');
        }
    }

    /**
     * @throws Exception
     */
    private function setKeySchema(): void
    {
        $diff = array_diff($this->currentSchema['KeySchema'], $this->describedSchema['KeySchema']);
        if (count($diff) > 0) {
            throw new Exception('updateTable doesn\'t support changing the table key schema');
        }
    }

    private function setAttributeDefinitions(): void
    {
        $this->updateSchema['AttributeDefinitions'] = $this->currentSchema['AttributeDefinitions'];
    }

    private function setProvisionThroughput(): void
    {
        $this->updateSchema['ProvisionedThroughput']['ReadCapacityUnits'] = $this->currentSchema['ProvisionedThroughput']['ReadCapacityUnits'];
        $this->updateSchema['ProvisionedThroughput']['WriteCapacityUnits'] = $this->currentSchema['ProvisionedThroughput']['WriteCapacityUnits'];
    }

    private function setGlobalSecondaryIndexes(): void
    {
        $addedParameters = array_diff($this->currentSchema, $this->describedSchema);
        foreach ($addedParameters as $addedProperty) {
            $this->updateSchema['GlobalSecondaryIndexUpdates'][] = [
                'Create' => [
                    'IndexName' => '',
                ],
            ];
        }

        $removedParameters = array_diff($this->describedSchema, $this->currentSchema);
        foreach ($removedParameters as $removedParameter) {
            $this->updateSchema['GlobalSecondaryIndexUpdates'][] = [
                'Delete' => [
                    'IndexName' => '',
                ],
            ];
        }

        $updatedParameters = [];
        foreach ($updatedParameters as $updatedParameter) {
            $this->updateSchema['GlobalSecondaryIndexUpdates'][] = [
                'Update' => [
                    'IndexName' => '',
                ],
            ];
        }
    }

}
